package com.anadi.prabhupadalectures.network.api.dumy

import com.anadi.prabhupadalectures.network.KtorClientFactory
import kotlinx.serialization.Serializable

interface UserApi {
    suspend fun getUsers(page: Int, limit: Int = 20): Users
    suspend fun getUser(id: Int): User
}

fun createUserApi(): UserApi =
    UserApiImpl(KtorClientFactory().build())

@Serializable
data class Users(
    val data: List<UserPreview>,
    val total: Int, // (total items in DB)
    val page: Int, // (current page 0 based)
    val limit: Int //(number of items on page)
)

@Serializable
data class UserPreview(
    val id: String, // (autogenerated)
    val title: String, // ("mr", "ms", "mrs", "miss", "dr", "")
    val firstName: String, // (length: 2-50)
    val lastName: String, // (length: 2-50)
    val picture: String, // (url)
) {
    val fullName
        get() = "$title. $firstName $lastName"
}

@Serializable
data class User(
    val id: String, // autogenerated)
    val title: String, // "mr", "ms", "mrs", "miss", "dr", "")
    val firstName: String, // length: 2-50)
    val lastName: String, // length: 2-50)
    val gender: String, // "male", "female", "other", "")
    val email: String, // email)
    val dateOfBirth: String, // ISO Date - value: 1/1/1900 - now)
    val registerDate: String, // autogenerated)
    val phone: String, // phone number - any format)
    val picture: String, // url)
    val location: Location
)

@Serializable
data class Location(
    val street: String, // length: 5-100)
    val city: String, // length: 2-30)
    val state: String, // length: 2-30)
    val country: String, // length: 2-30)
    val timezone: String // Valid timezone value ex. +7:00, -1:00)
)
