package com.listentoprabhupada.android_ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF974900)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDBC7)
val md_theme_light_onPrimaryContainer = Color(0xFF311300)
val md_theme_light_secondary = Color(0xFF8B5000)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDCBE)
val md_theme_light_onSecondaryContainer = Color(0xFF2C1600)
val md_theme_light_tertiary = Color(0xFF944B00)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDCC5)
val md_theme_light_onTertiaryContainer = Color(0xFF301400)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF6FEFF)
val md_theme_light_onBackground = Color(0xFF001F24)
val md_theme_light_surface = Color(0xFFF6FEFF)
val md_theme_light_onSurface = Color(0xFF001F24)
val md_theme_light_surfaceVariant = Color(0xFFF4DED3)
val md_theme_light_onSurfaceVariant = Color(0xFF52443C)
val md_theme_light_outline = Color(0xFF84746A)
val md_theme_light_inverseOnSurface = Color(0xFFD0F8FF)
val md_theme_light_inverseSurface = Color(0xFF00363D)
val md_theme_light_inversePrimary = Color(0xFFFFB687)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF974900)

val md_theme_dark_primary = Color(0xFFFFB687)
val md_theme_dark_onPrimary = Color(0xFF512400)
val md_theme_dark_primaryContainer = Color(0xFF733600)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDBC7)
val md_theme_dark_secondary = Color(0xFFFFB870)
val md_theme_dark_onSecondary = Color(0xFF4A2800)
val md_theme_dark_secondaryContainer = Color(0xFF693C00)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDCBE)
val md_theme_dark_tertiary = Color(0xFFFFB783)
val md_theme_dark_onTertiary = Color(0xFF4F2500)
val md_theme_dark_tertiaryContainer = Color(0xFF703700)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDCC5)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F24)
val md_theme_dark_onBackground = Color(0xFF97F0FF)
val md_theme_dark_surface = Color(0xFF001F24)
val md_theme_dark_onSurface = Color(0xFF97F0FF)
val md_theme_dark_surfaceVariant = Color(0xFF52443C)
val md_theme_dark_onSurfaceVariant = Color(0xFFD7C3B8)
val md_theme_dark_outline = Color(0xFF9F8D83)
val md_theme_dark_inverseOnSurface = Color(0xFF001F24)
val md_theme_dark_inverseSurface = Color(0xFF97F0FF)
val md_theme_dark_inversePrimary = Color(0xFF974900)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB687)

val seed = Color(0xFFD0690D)

